import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  education: [{ type: "autogenerated", dirName: "education" }],
};

export default sidebars;
